Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.8/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/Cellar/python@3.8/3.8.11/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.8/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/local/lib/python3.8/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
w = interactive(recommendations, radio.value)
display(w)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
[0;32m/var/folders/6n/6jrs9zvs35b405z7ck19fpwm0000gn/T/ipykernel_60643/3258080851.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mw[0m [0;34m=[0m [0minteractive[0m[0;34m([0m[0mrecommendations[0m[0;34m,[0m [0mradio[0m[0;34m.[0m[0mvalue[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0mdisplay[0m[0;34m([0m[0mw[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.8/site-packages/ipywidgets/widgets/interaction.py[0m in [0;36m__init__[0;34m(self, _interactive__interact_f, _interactive__options, **kwargs)[0m
[1;32m    182[0m         [0mself[0m[0;34m.[0m[0mf[0m [0;34m=[0m [0mf[0m [0;34m=[0m [0m__interact_f[0m[0;34m[0m[0;34m[0m[0m
[1;32m    183[0m         [0mself[0m[0;34m.[0m[0mclear_output[0m [0;34m=[0m [0mkwargs[0m[0;34m.[0m[0mpop[0m[0;34m([0m[0;34m'clear_output'[0m[0;34m,[0m [0;32mTrue[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 184[0;31m         [0mself[0m[0;34m.[0m[0mmanual[0m [0;34m=[0m [0m__options[0m[0;34m.[0m[0mget[0m[0;34m([0m[0;34m"manual"[0m[0;34m,[0m [0;32mFalse[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    185[0m         [0mself[0m[0;34m.[0m[0mmanual_name[0m [0;34m=[0m [0m__options[0m[0;34m.[0m[0mget[0m[0;34m([0m[0;34m"manual_name"[0m[0;34m,[0m [0;34m"Run Interact"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    186[0m         [0mself[0m[0;34m.[0m[0mauto_display[0m [0;34m=[0m [0m__options[0m[0;34m.[0m[0mget[0m[0;34m([0m[0;34m"auto_display"[0m[0;34m,[0m [0;32mFalse[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mAttributeError[0m: 'int' object has no attribute 'get'
AttributeError: 'int' object has no attribute 'get'

